# Generated by Django 4.2.16 on 2024-09-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, unique=True)),
                ('state', models.CharField(choices=[('U', 'Неопределённое состояние'), ('L', 'Утерян'), ('O', 'У клиента'), ('R', 'Готов к выдаче')], default='U', max_length=1)),
            ],
        ),
    ]
